"use client";
import * as React from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import NavBarUI from "@/components/NavbarUI";
import { motion } from "framer-motion";
import { Footer } from "@/components";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <NextUIProvider>
          <div className="main">
            <motion.div
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 0.6, scale: 1 }}
              transition={{ delay: 0.2, duration: 1.5 }}
              className="gradient"
            />
          </div>
          <NavBarUI />
          <main className="app">
            {/* <NavBar /> */}
            {children}
            <Footer />
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
